"""
Report builder — converts clause assessments into a structured JSON report
and a professional, user-friendly Markdown report.
"""
from __future__ import annotations

from collections import Counter
from typing import Any


DISCLAIMER = (
    "⚠️ **Legal Disclaimer:** This report is generated by an academic AI research prototype "
    "that combines classical machine-learning risk classification with large-language-model "
    "commentary. It is **not legal advice**, is not exhaustive, and may contain errors or "
    "omissions. Always consult a qualified legal professional before signing, modifying, "
    "or rejecting any contract clause."
)

_ACTION_ICONS = {
    "Remove Clause":       "🚫",
    "Negotiate Terms":     "🤝",
    "Seek Legal Review":   "⚖️",
    "Accept with Caution": "⚠️",
}

_RISK_ICONS = {
    "High":   "🔴",
    "Medium": "🟠",
    "Low":    "🟢",
}

_RISK_LABELS = {
    "High":   "HIGH RISK",
    "Medium": "MEDIUM RISK",
    "Low":    "LOW RISK",
}


# ---------------------------------------------------------------------------
# Structured JSON report
# ---------------------------------------------------------------------------

def build_structured_report(
    contract_overview: str,
    clause_assessments: list[dict[str, Any]],
) -> dict[str, Any]:
    risks  = [c.get("risk_level", "") for c in clause_assessments]
    counts = Counter(risks)

    flagged = []
    for c in clause_assessments:
        a = c.get("analysis") or {}
        flagged.append({
            # ML layer
            "clause_text":       c.get("clause_text", ""),
            "model_risk_level":  c.get("risk_level"),
            "model_confidence":  c.get("confidence"),
            "retrieved_practice_ids": [p.get("id") for p in c.get("best_practices", [])],
            # LLM layer (8 fields)
            "plain_english_summary":      a.get("plain_english_summary", ""),
            "what_makes_it_risky":        a.get("what_makes_it_risky", ""),
            "who_bears_the_risk":         a.get("who_bears_the_risk", ""),
            "severity_rationale":         a.get("severity_rationale", ""),
            "industry_standard_practice": a.get("industry_standard_practice", ""),
            "negotiation_tips":           a.get("negotiation_tips", ""),
            "safer_rewrite":              a.get("safer_rewrite", ""),
            "action_required":            a.get("action_required", "Seek Legal Review"),
        })

    return {
        "contract_overview":     contract_overview,
        "risk_severity_breakdown": {
            "High":   int(counts.get("High",   0)),
            "Medium": int(counts.get("Medium", 0)),
            "Low":    int(counts.get("Low",    0)),
        },
        "flagged_clauses_and_mitigation": flagged,
        "disclaimer": DISCLAIMER,
    }


# ---------------------------------------------------------------------------
# Markdown report renderer
# ---------------------------------------------------------------------------

def render_markdown_report(report: dict[str, Any]) -> str:
    b      = report["risk_severity_breakdown"]
    high   = int(b.get("High",   0))
    medium = int(b.get("Medium", 0))
    low    = int(b.get("Low",    0))
    total  = high + medium + low

    # ── Overall risk signal ───────────────────────────────────────────────────
    if high >= 2:
        overall_signal = "🔴 **HIGH RISK DOCUMENT** — Multiple critical issues detected."
    elif high == 1:
        overall_signal = "🟠 **ELEVATED RISK** — At least one critical clause requires attention."
    elif medium >= 2:
        overall_signal = "🟡 **MODERATE RISK** — Several clauses need review."
    else:
        overall_signal = "🟢 **LOWER RISK** — Minor concerns only. Standard review recommended."

    lines: list[str] = [
        "---",
        "# 📋 Contract Risk Assessment Report",
        "---",
        "",
        "## 📌 Executive Summary",
        "",
        f"> {report.get('contract_overview', '(No overview available.)')}",
        "",
        f"**Overall Signal:** {overall_signal}",
        "",
        "### Risk Breakdown",
        "",
        f"| Severity | Count | Meaning |",
        f"|----------|-------|---------|",
        f"| 🔴 High   | **{high}** | Requires immediate attention or renegotiation |",
        f"| 🟠 Medium | **{medium}** | Should be reviewed and potentially amended |",
        f"| 🟢 Low    | **{low}** | Minor concern; acceptable with awareness |",
        f"| **Total** | **{total}** | Clauses assessed by the AI agent |",
        "",
        "---",
        "## 🔍 Clause-by-Clause Analysis",
        "",
    ]

    clauses = report.get("flagged_clauses_and_mitigation", [])
    high_clauses   = [c for c in clauses if c.get("model_risk_level") == "High"]
    medium_clauses = [c for c in clauses if c.get("model_risk_level") == "Medium"]
    low_clauses    = [c for c in clauses if c.get("model_risk_level") == "Low"]

    ordered = high_clauses + medium_clauses + low_clauses

    for i, row in enumerate(ordered, 1):
        risk        = row.get("model_risk_level", "Unknown")
        conf        = float(row.get("model_confidence") or 0)
        action      = row.get("action_required", "Seek Legal Review")
        action_icon = _ACTION_ICONS.get(action, "⚖️")
        risk_icon   = _RISK_ICONS.get(risk, "⚪")
        risk_label  = _RISK_LABELS.get(risk, risk.upper())
        who         = row.get("who_bears_the_risk", "Unknown")

        lines.extend([
            f"### {risk_icon} Clause {i} — {risk_label}",
            "",
            f"| | |",
            f"|---|---|",
            f"| **ML Confidence** | {conf:.0%} |",
            f"| **Risk Bearer**   | {who} |",
            f"| **Action**        | {action_icon} {action} |",
            "",
            "#### 📄 Original Clause Text",
            "",
            f"> {row.get('clause_text', '').strip()}",
            "",
            "#### 💬 What This Clause Says (Plain English)",
            "",
            row.get("plain_english_summary", "—"),
            "",
            "#### ⚠️ Why This Is Risky",
            "",
            row.get("what_makes_it_risky", "—"),
            "",
            "#### 📊 Why It Was Rated " + risk,
            "",
            row.get("severity_rationale", "—"),
            "",
            "#### 📚 Industry Standard Practice",
            "",
            row.get("industry_standard_practice", "—"),
            "",
            "#### 🤝 Negotiation Tips",
            "",
            row.get("negotiation_tips", "—"),
            "",
            "#### ✅ Suggested Safer Wording",
            "",
            "```",
            row.get("safer_rewrite", "—"),
            "```",
            "",
            "---",
            "",
        ])

    # ── Action summary table ──────────────────────────────────────────────────
    lines.extend([
        "## 📋 Action Summary",
        "",
        "| # | Risk | Action Required | Clause Preview |",
        "|---|------|-----------------|----------------|",
    ])
    for i, row in enumerate(ordered, 1):
        risk       = row.get("model_risk_level", "?")
        risk_icon  = _RISK_ICONS.get(risk, "⚪")
        action     = row.get("action_required", "Seek Legal Review")
        action_icon= _ACTION_ICONS.get(action, "⚖️")
        preview    = row.get("clause_text", "")[:60].replace("\n", " ").strip()
        lines.append(
            f"| {i} | {risk_icon} {risk} | {action_icon} {action} | {preview}… |"
        )

    lines.extend([
        "",
        "---",
        "## ⚠️ Disclaimer",
        "",
        DISCLAIMER,
        "",
        "---",
        "*Generated by the Intelligent Contract Risk Analysis System · Phase 2 (Agentic AI)*",
    ])

    return "\n".join(lines)
