"""
contract_agent/report.py — Report Builder
=========================================

Converts clause assessments into two output formats:

  1. `structured_report` — a JSON dict for interactive Streamlit rendering
  2. `render_markdown_report` — a clean, simplified 4-section markdown report
       containing exactly: Summary | Deep Dive | Mitigation | Disclaimer
"""
from __future__ import annotations

from collections import Counter
from typing import Any


DISCLAIMER = (
    "⚠️ **Legal Disclaimer:** This report is generated by an academic AI research prototype "
    "that combines classical machine-learning risk classification with large-language-model "
    "commentary. It is **not legal advice**, is not exhaustive, and may contain errors or "
    "omissions. Always consult a qualified legal professional before signing, modifying, "
    "or rejecting any contract clause."
)

_ACTION_ICONS = {
    "Remove Clause":       "",
    "Negotiate Terms":     "",
    "Seek Legal Review":   "",
    "Accept with Caution": "",
}

_RISK_ICONS = {
    "High":   "",
    "Medium": "",
    "Low":    "",
}

_RISK_LABELS = {
    "High":   "HIGH RISK",
    "Medium": "MEDIUM RISK",
    "Low":    "LOW RISK",
}


# ─────────────────────────────────────────────────────────────────────────────
# Structured JSON report (for Streamlit interactive UI)
# ─────────────────────────────────────────────────────────────────────────────

def build_structured_report(
    contract_overview:  str,
    clause_assessments: list[dict[str, Any]],
    domain:             str = "General",
) -> dict[str, Any]:
    risks  = [c.get("risk_level", "") for c in clause_assessments]
    counts = Counter(risks)

    flagged = []
    for c in clause_assessments:
        a = c.get("analysis") or {}
        flagged.append({
            # ML layer
            "clause_text":             c.get("clause_text", ""),
            "model_risk_level":        c.get("risk_level"),
            "model_confidence":        c.get("confidence"),
            "retrieved_practice_ids":  [p.get("id") for p in c.get("best_practices", [])],
            "retrieved_domain":        domain,
            # LLM layer (8 fields)
            "plain_english_summary":      a.get("plain_english_summary",      ""),
            "what_makes_it_risky":        a.get("what_makes_it_risky",        ""),
            "who_bears_the_risk":         a.get("who_bears_the_risk",         ""),
            "severity_rationale":         a.get("severity_rationale",         ""),
            "industry_standard_practice": a.get("industry_standard_practice", ""),
            "negotiation_tips":           a.get("negotiation_tips",           ""),
            "safer_rewrite":              a.get("safer_rewrite",              ""),
            "action_required":            a.get("action_required", "Seek Legal Review"),
        })

    return {
        "contract_overview":          contract_overview,
        "domain":                     domain,
        "risk_severity_breakdown":    {
            "High":   int(counts.get("High",   0)),
            "Medium": int(counts.get("Medium", 0)),
            "Low":    int(counts.get("Low",    0)),
        },
        "flagged_clauses_and_mitigation": flagged,
        "disclaimer": DISCLAIMER,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Simplified markdown report — 4 sections: Summary | Deep Dive | Mitigation | Disclaimer
# ─────────────────────────────────────────────────────────────────────────────

def render_markdown_report(report: dict[str, Any]) -> str:
    b      = report["risk_severity_breakdown"]
    high   = int(b.get("High",   0))
    medium = int(b.get("Medium", 0))
    low    = int(b.get("Low",    0))
    total  = high + medium + low
    domain = report.get("domain", "General")

    # Overall risk signal
    if high >= 2:
        overall = f"🔴 **HIGH RISK** — {high} critical clause(s) require immediate attention or rejection."
    elif high == 1:
        overall = "🟠 **ELEVATED RISK** — 1 critical clause must be renegotiated before signing."
    elif medium >= 2:
        overall = f"🟡 **MODERATE RISK** — {medium} clauses need review and possible amendment."
    else:
        overall = "🟢 **LOWER RISK** — Minor concerns only. Standard legal review recommended."

    clauses = report.get("flagged_clauses_and_mitigation", [])
    ordered = (
        [c for c in clauses if c.get("model_risk_level") == "High"] +
        [c for c in clauses if c.get("model_risk_level") == "Medium"]
    )

    lines: list[str] = [
        "# 📋 Contract Risk Report",
        "",
        f"**Contract Type:** {domain}  |  "
        f"**Clauses Reviewed:** {total}  |  "
        f"🔴 {high} High · 🟠 {medium} Medium",
        "",
        "---",
        "",
        "## 1. Summary",
        "",
        f"> {report.get('contract_overview', '(No overview available.)')}",
        "",
        f"**Overall Risk:** {overall}",
        "",
        "| Risk Level | Count |",
        "|------------|-------|",
        f"| High    | **{high}** |",
        f"| Medium  | **{medium}** |",
        f"| Low     | {low} (filtered — not sent to AI) |",
        "",
        "---",
        "",
        "## 2. Deep Dive — Why Each Clause Is Risky",
        "",
    ]

    for i, row in enumerate(ordered, 1):
        risk   = row.get("model_risk_level", "Unknown")
        conf   = float(row.get("model_confidence") or 0)
        action = row.get("action_required", "Seek Legal Review")
        who    = row.get("who_bears_the_risk", "Unknown")

        preview = row.get("clause_text", "")[:100].replace("\n", " ").strip()

        lines += [
            f"### Clause {i} — {_RISK_LABELS.get(risk, risk)}",
            "",
            f"**Risk Bearer:** {who}  |  **ML Confidence:** {conf:.0%}  |  **Action:** {action}",
            "",
            f"> *\"{preview}…\"*",
            "",
            "**What it actually says:**",
            row.get("plain_english_summary", "—"),
            "",
            "**Why it is risky:**",
        ]

        # Render bullet points if the text looks like a list already
        risky_text = row.get("what_makes_it_risky", "—")
        lines.append(risky_text)
        lines.append("")

        lines += [
            f"**Industry standard ({domain}):**",
            row.get("industry_standard_practice", "—"),
            "",
        ]

    lines += [
        "---",
        "",
        "## 3. Mitigation — How to Fix Each Clause",
        "",
    ]

    for i, row in enumerate(ordered, 1):
        risk = row.get("model_risk_level", "Unknown")

        lines += [
            f"### Clause {i}",
            "",
            "**Negotiation steps:**",
            row.get("negotiation_tips", "1. Seek legal review before signing."),
            "",
            "**Suggested safer wording:**",
            "```",
            row.get("safer_rewrite", "(Manual review required)"),
            "```",
            "",
        ]

    # Action summary table
    lines += [
        "---",
        "",
        "### Action Summary",
        "",
        "| # | Risk | Action | Clause |",
        "|---|------|--------|--------|",
    ]
    for i, row in enumerate(ordered, 1):
        risk   = row.get("model_risk_level", "?")
        action = row.get("action_required", "Seek Legal Review")
        prev   = row.get("clause_text", "")[:60].replace("\n", " ").strip()
        lines.append(f"| {i} | {risk} | {action} | {prev}… |")

    lines += [
        "",
        "---",
        "",
        "## 4. Disclaimer",
        "",
        DISCLAIMER,
        "",
        "---",
        "*Generated by the Intelligent Contract Risk Analysis System — Milestone 2 (Agentic AI + Domain-Aware RAG)*",
    ]

    return "\n".join(lines)
